spring.application.name=progreso2-integracion-mora-jostin
server.port=8080

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

app.error.file=data/errors/citas-rechazadas.log
app.routing.billing-endpoint=spring-rabbitmq:billing.exchange?routingKey=billing.queue
app.routing.events-endpoint=spring-rabbitmq:appointments.events
app.routing.audit-endpoint=file:data/outbox?fileName=auditoria-citas.csv&fileExist=Append&charset=UTF-8
